### ISSUE TITLE
'spi_bcm2708': No such device

### ISSUE THREAD

**Issue by WilHowitt** [sparkfun/Pi_Wedge_B_Plus#7]
I can build the SparkFun_spitest.cpp with no problem, but when I try to load the SPI module, I get this error:

$ gpio load spi
ERROR: could not insert 'spi_bcm2708': No such device
gpio: Unable to load spi_bcm2708

I don't know if this error is specific to this file or not . . . can you help me out?

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I just noticed your question when browsing the issues tab. If you have not already solved the problem, it might be due to the Pi's  image used at the time. This is probably due to the way the kernel was built when you filed the issue => [ [https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=97314](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=97314). Try checking the section where it says "**Fixing the Problem**".  I found the forum link after entering the command in the Pi's command line using the latest image.  

Doing a search with the error that you had, it seems to match the issue with the kernel using **spi_bcm2835.ko** as opposed to **spi_bcm,2708.ko** => [ [https://www.raspberrypi.org/forums/viewtopic.php?p=793284&sid=09141fb98ec91a5e1413def769ad257e#p793284(https://www.raspberrypi.org/forums/viewtopic.php?p=793284&sid=09141fb98ec91a5e1413def769ad257e#p793284) . 

If you are still having issues, you may want to post on the [Raspberry Pi](https://www.raspberrypi.org/forums/) or the [SparkFun Forums](https://forum.sparkfun.com/viewforum.php?f=100) to see if anyone has run into this specific case.
